# Generated by Django 5.1.5 on 2025-02-06 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='blog.categoria', verbose_name='categorias'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
